ansible-vars: add detection
Until now, the scripts sometimes have strange effects if the ansible
vars are not sourced. Check explicitly.

Signed-off-by: Robert Schwebel <robert@schwebel.de>

diff --git a/bin/ffhivnet-list b/bin/ffhivnet-list
--- a/bin/ffhivnet-list
+++ b/bin/ffhivnet-list
@@ -6,5 +6,10 @@ if [  $# -ne 0 ]; then
 	echo "Usage: $0"
 	exit 1
 fi
+
+if [ -n "$ANSIBLE_VARS_SOURCED" ]; then
+	echo "Error: did you 'source ansible-vars'?"
+	exit 1
+fi
  
 virsh --connect=qemu:///system net-list --all
diff --git a/bin/ffhivnet-up b/bin/ffhivnet-up
--- a/bin/ffhivnet-up
+++ b/bin/ffhivnet-up
@@ -7,6 +7,11 @@ if [  $# -ne 0 ]; then
 	exit 1
 fi
 
+if [ -n "$ANSIBLE_VARS_SOURCED" ]; then
+	echo "Error: did you 'source ansible-vars'?"
+	exit 1
+fi
+
 # filter host+address definitions from inventory into definition of
 # virtual network
 
@@ -19,4 +24,3 @@ virsh --connect=qemu:///system net-start ffhivnet
 virsh --connect=qemu:///system net-list
 
 rm -f $VNET_XML_TMP
-
diff --git a/bin/vm-bootstrap b/bin/vm-bootstrap
--- a/bin/vm-bootstrap
+++ b/bin/vm-bootstrap
@@ -16,6 +16,11 @@ if [  $# -ne 1 ]; then
 	echo "Usage: $0 guest-name"
 	exit 1
 fi
+
+if [ -n "$ANSIBLE_VARS_SOURCED" ]; then
+	echo "Error: did you 'source ansible-vars'?"
+	exit 1
+fi
  
 virt-install \
 	--nographics \
diff --git a/bin/vm-destroy b/bin/vm-destroy
--- a/bin/vm-destroy
+++ b/bin/vm-destroy
@@ -6,6 +6,11 @@ if [  $# -ne 1 ]; then
 	virsh --connect=qemu:///system list --all
 	exit 1
 fi
+
+if [ -n "$ANSIBLE_VARS_SOURCED" ]; then
+	echo "Error: did you 'source ansible-vars'?"
+	exit 1
+fi
  
 virsh --connect=qemu:///system destroy ${1} > /dev/null 2>&1 
 virsh --connect=qemu:///system undefine ${1} > /dev/null 2>&1
diff --git a/bin/vm-list b/bin/vm-list
--- a/bin/vm-list
+++ b/bin/vm-list
@@ -5,4 +5,9 @@ if [  $# -ne 0 ]; then
 	exit 1
 fi
 
+if [ -n "$ANSIBLE_VARS_SOURCED" ]; then
+	echo "Error: did you 'source ansible-vars'?"
+	exit 1
+fi
+
 virsh --connect=qemu:///system list --all
